---
title: "Literate Programming Based Improvements To Chapter 1 of GWH2013a"
author: "Peter von Rohr"
date: "29 Jan 2015"
layout: post
output:
  html_document:
    keep_md: no
    theme: united
    mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
references:
- URL: http://www.springer.com/life+sciences/systems+biology+and+bioinformatics/book/978-1-62703-446-3
  author:
  - family: Gondro
    given: Cedric
  - family: van der Werf
    given: Julius
  - family: Hayes
    given: Ben
  id: GWH2013a
  issued:
    year: 2013
  title: Genome-Wide Association Studies and Genomic Prediction
---

## Disclaimer
This document summarizes the content of chapter 1 of [@GWH2013a]. The main objective of this summary is to transform the summarized text and the programming code between the text into a document based on the paradigm of [`Literate Programming`](http://en.wikipedia.org/wiki/Literate_programming). 

## Chapter 1 - R for Genome Wide Association Studies

### Abstract
The authors state that R has become the de facto language of choice for statisticians and that it is the most widely used environment for analysing high-throughput genomic data. While these statements are certainly not wrong, one has to keep in mind that most of statistical analyses are probably still done in MS Excel. But despite that fact I would never recommend to anyone to use MS Excel for any statistical analysis. Or more generally I would not make any recommendation of a product only based on the fact that a large number of people use that product. From my point of view, R is widely used because it has a very active and supportive community and that problems are solved much quicker than in any other commericially available products. 

### Section 1 - Introduction
The introduction starts with the same statements as were already mentioned at the begining of the abstract. Do not get me wrong here, I am not critisizing the authors here for saying anything wrong, but I find those arguments not so convincing. Part of the problem is also that no examples of R-code snippets are shown to support their argument. 

Let me add two points in favor of R that I would use to convince people to use R. For all those readers who are not interested in these arguments or for all those who are already convinced of R, can safely skip the remainder of this subsection and can jump to the summary of section 2 of chapter 1 of [@GWH2013a].

My favorite two arguments in favor of R are

1. `Fast Prototyping` - which means that ideas are quickly converted into R-code and
2. `Literate Programming` - R provides a lot of infrastructure to implement the paradigm of literate programming. 

For all those who want to know more about the above two points, please read the post entitled [Why R](http://charlotte-ngs.github.io/WhyR/notes/20150203-WhyR.html). 

After this short digression, let us get back to [@GWH2013a]


## Section 2 - Reading Data into R
It is true that it takes time to read genomic data of a certain size into R, but this is true for any system. Using the same example as in [@GWH2013a], the following timings result

```{r}
(ptReadTable  <- system.time(myData <- read.table(file = "../data/square.txt", sep = "\t")))
dim(myData)
```

As a very small side note, when looking at the dimension of the data.frame `myData`, we can see that it has `r ncol(myData)` columns. According to [Excel specifications and limits](https://support.office.microsoft.com/en-us/article/Excel-specifications-and-limits-ca36e2dc-1f09-4620-b726-67c00b05040f?CTT=1&CorrelationId=f389929d-fd39-4369-b67d-a8061edd2258&ui=en-US&rs=en-US&ad=US) the number of columns that can be read into a single worksheet in Excel is still limited to 16,384 which makes it clearly impossible to read this dataset into a single worksheet of MS Excel. I clearly prefer waiting for `r as.numeric(ptReadTable[3])` seconds until the data is read compared to not being able to read the data at all. 

Specifying 



```
To be continued ...
```

## References
